return PlaceObj('ModDef', {
	'title', "Pinned Down",
	'description', "This mod introduces a suppression system, which is reflected in 5 new combat effects. While a counter tracks the suppression for each unit in the background, your units and opponents can acquire the following statuses:\n\n[list]\n[*]Shot At\n[*]Under Fire\n[*]Under Heavy Fire\n[*]Suppressed\n[*]Pinned down\n[/list]\n\nThe higher the status, the fewer APs are available to your characters in the next round and, in the case of interrupts, also in this round. In addition, units run the risk of panicking or going berserk.\n\nHowever, not every enemy and Merc reacts exactly the same to fire, but depending on experience or psychological constitution, have a certain resilience to suppression. Also, someone in good protective gear feels safer in a hail of bullets than someone in jeans and a t-shirt.\n\nIf the suppression is too much or too little for you, you will find two sliders in the mod options to influence it. \n\nI recommend to set the suppression multiplier in the mod options to 200% to get a realistic suppression simulation.\n\nThe whole thing was tested with the vanilla version of the game, but it should also run with mods that don’t change the vanilla character property “Suppressed”.\n\nMods can also easily override the suppression values of weapon types and combat actions.\n\nIf you find that the balance still needs to be tweaked, or you stumble upon a bug, please let me know.\n\n[b]Known Issues[/b]\n\nSometimes it can happen that someone who appears a little further away also receives suppression. This happens when a bullet hits quite far from the shot and the unit is nearby. This would be avoidable, but the game has to calculate quite a lot for this mod and it is rather the exception.\n\nThanks to everyone on the JA3 Modding Discord. Especially to audaki_ra and Tobias for their help.",
	'image', "Mod/ANKmKG/Images/_ff5ac272-5b19-4c5a-9273-62339c653f25.png",
	'last_changes', "[list]\n[*]Increased suppression reistance for same side and animals \n[/list]",
	'id', "ANKmKG",
	'author', "permanent666",
	'version_major', 5,
	'version_minor', 1,
	'version', 1282,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"CharacterEffect/ShotAt.lua",
		"CharacterEffect/UnderFire.lua",
		"CharacterEffect/UnderHeavyFire.lua",
		"CharacterEffect/SuppressedCustom.lua",
		"CharacterEffect/PinnedDown.lua",
		"CharacterEffect/Suppressed.lua",
		"Code/Config.lua",
		"Code/Options.lua",
		"Code/SuppressionMeter.lua",
	},
	'default_options', {
		suppressed_consumed_aps_log_level = "debug (visible only in debug mode)",
		suppressed_suppression_ai_multiplier = "100",
		suppressed_suppression_multiplier = "100",
		suppressed_suppression_player_multiplier = "100",
	},
	'has_data', true,
	'saved', 1724618223,
	'code_hash', 16621549124701179,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ShotAt",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "UnderFire",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "UnderHeavyFire",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SuppressedCustom",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "PinnedDown",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Suppressed",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_test_mode",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_mod_active",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_consumed_ap_per_level",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_max_removed",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_multiplier",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_ai_multiplier",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_player_multiplier",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_resitance_multiplier",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_armor_resistance_multiplier",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_state_treshold_shot_at",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_state_treshold_under_fire",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_state_treshold_under_heavy_fire",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_state_treshold_suppressed_custom",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_state_treshold_pinned_down",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_vanilla_value",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_panic_treshold",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "suppression_panic_treshold",
			'ClassDisplayName', "Constant",
		}),
	},
	'steam_id', "3019207726",
})