return PlaceObj('ModDef', {
	'title', "Suppressed",
	'id', "ANKmKG",
	'content_path', "Mod/ANKmKG/",
	'author', "permanent666",
	'version', 1113,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"CharacterEffect/ShotAt.lua",
		"CharacterEffect/UnderFire.lua",
		"CharacterEffect/UnderHeavyFire.lua",
		"CharacterEffect/SuppressedCustom.lua",
		"CharacterEffect/PinnedDown.lua",
		"CharacterEffect/Suppressed.lua",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"Code/Config.lua",
		"Code/Options.lua",
		"Code/SuppressionMeter.lua",
	},
	'has_options', true,
	'saved', 1691870935,
	'code_hash', -3305110685275737903,
})